/* SPDX-License-Identifier: MIT
 * moe_router.h — GENERATED by tools/gen_moe_router.py from
 * training/moe_shards.py.
 *
 * The ROM router must perform the SAME match the training labels used, or a
 * prompt trains into one expert and routes to another at runtime. Generating
 * this table from the trainer's own list is what makes that impossible; do not
 * hand-edit. Plain lowercase substring, first shard whose keyword hits wins,
 * order matters (specific topics precede general ones).
 */
#ifndef MOE_ROUTER_H
#define MOE_ROUTER_H

#include <string.h>
#include <stdint.h>

#define MOE_N_EXPERTS 5
#define MOE_E_RUSTCHAIN 0
#define MOE_E_HARDWARE 1
#define MOE_E_DUNGEON 2
#define MOE_E_LORE 3
#define MOE_E_IDENTITY 4

static const char *const moe_expert_name[MOE_N_EXPERTS] = {
    "rustchain",
    "hardware",
    "dungeon",
    "lore",
    "identity",
};

static const char *const moe_k_rustchain[] = {
    "rustchain",
    "rtc",
    "proof of antiquity",
    "proof of work",
    "epoch",
    "node",
    "mining",
    "mine ",
    "blockchain",
    "token",
    "wallet",
    "ledger",
    "antiquity",
    "attestation",
    "settle",
    0
};
static const char *const moe_k_hardware[] = {
    "g4",
    "g5",
    "power8",
    "altivec",
    "vec_perm",
    "vr4300",
    "mips",
    "n64",
    "console",
    "cartridge",
    "cpu",
    "silicon",
    "chip",
    "ram",
    "expansion pak",
    "model",
    "weights",
    "kilobytes",
    "parameters",
    "language runs you",
    "runs this rom",
    "hardware",
    "simd",
    "threads",
    "powerpc",
    "amiga",
    "68k",
    "sparc",
    "vintage",
    "rsp",
    "rdram",
    "processor",
    "transistor",
    "clock speed",
    "megahertz",
    "mhz",
    0
};
static const char *const moe_k_dungeon[] = {
    "lurks",
    "proceed",
    "need here",
    "secret",
    "dungeon",
    "wall",
    "crystal",
    "key",
    "door",
    "treasure",
    "ghost",
    "goblin",
    "spirit",
    "haunt",
    "triforce",
    "guard",
    "realm",
    "hero",
    "quest",
    "boss",
    "trap",
    "bomb",
    "lens",
    "gold",
    "tile",
    "shadow",
    "danger",
    "monster",
    0
};
static const char *const moe_k_lore[] = {
    "zelda",
    "link",
    "ganon",
    "hyrule",
    "kokiri",
    "lon lon",
    "ocarina",
    "deku",
    "triforce",
    "epona",
    "navi",
    "saria",
    "sheik",
    "termina",
    "nintendo",
    "nes",
    "snes",
    "n64 game",
    "mario",
    "samus",
    "metroid",
    "sega",
    "genesis",
    "amiga game",
    "arcade",
    "cartridge game",
    0
};

/* Lowercase a prompt into a bounded scratch buffer, then substring-match. */
static inline uint16_t moe_route(const char *prompt)
{
    char low[96];
    int n = 0;
    for (; prompt[n] && n < (int)sizeof(low) - 1; n++) {
        char c = prompt[n];
        low[n] = (c >= 'A' && c <= 'Z') ? (char)(c - 'A' + 'a') : c;
    }
    low[n] = 0;

    static const char *const *const tabs[] = {
        moe_k_rustchain,
        moe_k_hardware,
        moe_k_dungeon,
        moe_k_lore,
        0,
    };
    for (uint16_t e = 0; e < MOE_N_EXPERTS; e++) {
        const char *const *k = tabs[e];
        if (!k) return e;                 /* the catch-all shard */
        for (; *k; k++) if (strstr(low, *k)) return e;
    }
    return MOE_N_EXPERTS - 1;
}

#endif /* MOE_ROUTER_H */
