// SPDX-License-Identifier: MIT
/*
 * xchk_probe.c — on-console CPU-vs-RSP cross-check, printed on the screen.
 *
 * The RSP kernel's exactness record (docs/N64_RSP_FINDINGS.md F-R018/F-R023,
 * 176/176 tokens) was established OFF the console: an ares IS-Viewer log
 * compared by hand against a numpy oracle.  This ROM makes the console itself
 * state the claim, so a photo of a TV is the evidence:
 *
 *   the SAME ternary blob is loaded twice, one copy driven by the scalar
 *   VR4300 engine and one by the RSP engine (the copy the RSP owns is
 *   permuted in place at init and cannot be read by the CPU kernels again,
 *   which is why two copies are needed).  Both arms ingest the same prompt
 *   and free-run the same number of greedy tokens.  Every generated byte is
 *   compared, and the verdict is drawn on screen:
 *
 *       XCHK PASS 16/16 48/48    (or  XCHK FAIL at token N)
 *
 * along with the CP0 cycle count of each arm and their ratio, the RSP
 * dispatch counters (proving the RSP arm really went to the vector unit and
 * the CPU arm never did), and the largest |logit| difference seen across all
 * steps.  Tokens are the claim; the logit gap is reported, not gated, because
 * the two arms sum the block products in a different order (float per element
 * on the CPU, exact integer then one float16 scale on the RSP) and are not
 * expected to be bit-identical floats -- they are expected to pick the same
 * bytes, which is what a player would ever see.
 *
 * Mirrors everything to IS-Viewer and ends with XCHK_DONE, so
 * ~/aresroms/ares_run.sh can gate a headless run on it the same way the
 * BOOT_PROBE and DUAL_ builds are gated.
 *
 * Standalone main(), same reasons as dual_probe.c: it needs two models
 * resident and does not want the game's globals.  Build: make xchk
 */
#include <libdragon.h>
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include <stdarg.h>
#include "nano_gpt.h"

/* ------------------------------------------------------------------ clocks */
static volatile uint32_t g_vbl = 0;
static void vbl_counter(void) { g_vbl++; }
#define CP0(x) asm volatile("mfc0 %0, $9" : "=r"(x))

/* IS-Viewer text out.  32-BIT WRITES ONLY: byte stores silently drop three of
 * every four characters (F37). */
static char pl[256];
#define ISV(s) do {                                                        \
    const char *_s = (s);                                                  \
    uint32_t _n = (uint32_t)strlen(_s), _w = (_n + 3) & ~3u;               \
    for (uint32_t _i = 0; _i < _w; _i += 4) {                              \
        uint32_t _v = 0;                                                   \
        for (int _b = 0; _b < 4; _b++) {                                   \
            uint32_t _c = (_i + _b < _n) ? (uint8_t)_s[_i + _b] : 0;       \
            _v |= _c << (24 - 8 * _b);                                     \
        }                                                                  \
        *(volatile uint32_t *)(uintptr_t)(0xB3FF0020ul + _i) = _v;         \
    }                                                                      \
    *(volatile uint32_t *)(uintptr_t)(0xB3FF0014ul) = _n;                  \
} while (0)

/* ------------------------------------------------------------------ screen
 * A fixed list of lines, redrawn in full whenever one changes.  The 8x8 font
 * on 320x240 gives 40 columns; lines are kept under that. */
#define NLINES 26
static char scr[NLINES][40];
static int  scr_n = 0;

static void redraw(void)
{
    surface_t *disp = display_get();
    graphics_fill_screen(disp, 0);
    for (int i = 0; i < scr_n; i++)
        graphics_draw_text(disp, 8, 8 + 8 * i, scr[i]);
    display_show(disp);
}
static void say(const char *s)
{
    if (scr_n < NLINES) { strncpy(scr[scr_n], s, 39); scr[scr_n][39] = 0; scr_n++; }
    snprintf(pl, sizeof pl, "XCHK %s\n", s); ISV(pl);
    redraw();
}
static void sayf(const char *fmt, ...) __attribute__((format(printf, 1, 2)));
static void sayf(const char *fmt, ...)
{
    static char b[128];
    va_list ap; va_start(ap, fmt); vsnprintf(b, sizeof b, fmt, ap); va_end(ap);
    say(b);
}

/* ------------------------------------------------------------------- state */
static uint8_t wc_buf[SGAI_WEIGHT_BUF_N(2, SGAI_N_LAYERS)] __attribute__((aligned(16)));
static uint8_t wr_buf[SGAI_WEIGHT_BUF_N(2, SGAI_N_LAYERS)] __attribute__((aligned(16)));
static SGAIState   ST_C, ST_R;
static SGAIScratch SC_C, SC_R;

static int load_blob(const char *path, uint8_t *dst, int cap, int *out_sz)
{
    int fd = dfs_open(path);
    if (fd < 0) { *out_sz = -1; return 0; }
    int sz = dfs_size(fd);
    *out_sz = sz;
    if (sz <= 0 || sz > cap) { dfs_close(fd); return 0; }
    dfs_read(dst, 1, sz, fd);
    dfs_close(fd);
    return 1;
}

/* ----------------------------------------------------------------- one arm
 * Prompt ingestion then NGEN free-running greedy tokens, exactly the
 * BOOT_PROBE recipe (legend_of_elya.c) so the transcripts line up with the
 * F-R015/F-R018 oracle logs: out[0] is the prediction after the prompt. */
#define MAXGEN 48
static float lg_c[MAXGEN][SGAI_VOCAB];   /* CPU-arm logits per step, for the gap */
static float g_maxgap = 0.0f;

static uint32_t run_arm(SGAIState *st, const char *p, int ngen, uint8_t *out,
                        int keep_logits)
{
    uint32_t t0, t1, total = 0;
    uint8_t tok = 0;
    sgai_reset(st);
    for (int i = 0; p[i]; i++) tok = sgai_next_token(st, (uint8_t)p[i], 0);
    for (int i = 0; i < ngen; i++) {
        CP0(t0);
        if (i) tok = sgai_next_token(st, tok, 0);
        CP0(t1);
        total += (t1 - t0);
        out[i] = tok;
        if (keep_logits) memcpy(lg_c[i], st->logits, sizeof lg_c[i]);
        else {
            /* RSP arm: compare against the stored CPU logits for this step */
            for (int k = 32; k <= 126; k++) {
                float d = st->logits[k] - lg_c[i][k];
                if (d < 0) d = -d;
                if (d > g_maxgap) g_maxgap = d;
            }
        }
    }
    return total;
}
static void printable(const uint8_t *t, int n, char *dst)
{
    for (int i = 0; i < n; i++) dst[i] = (t[i] >= 32 && t[i] < 127) ? (char)t[i] : '?';
    dst[n] = 0;
}

/* -------------------------------------------------------------------- main */
struct probe { const char *prompt; int ngen; };
static const struct probe PROBES[] = {
    { "Elya",         16 },   /* F-R015 / F-R017 / F-R023 prompt */
    { "Who are you?", 48 },   /* F-R018 prompt */
};
#define NPROBES ((int)(sizeof PROBES / sizeof PROBES[0]))

int main(void)
{
    display_init(RESOLUTION_320x240, DEPTH_16_BPP, 2, GAMMA_NONE, ANTIALIAS_RESAMPLE);
    timer_init();
    register_VI_handler(vbl_counter);
    dfs_init(DFS_DEFAULT_LOCATION);
    rdpq_init();          /* brings rspq up; the matmul registers as an overlay */

    say("LEGEND OF ELYA - CPU vs RSP XCHK");
    say("rsp_mm2.S exactness, on this console");
    sayf("RDRAM %u KB  need 2x%u KB weights",
         (unsigned)(get_memory_size() / 1024), (unsigned)(sizeof wc_buf / 1024));

    int szc = 0, szr = 0;
    int okc = load_blob("/sophia_weights.bin", wc_buf, (int)sizeof wc_buf, &szc);
    int okr = load_blob("/sophia_weights.bin", wr_buf, (int)sizeof wr_buf, &szr);
    sayf("blob %d B x2 ok=%d%d", szc, okc, okr);
    if (!okc || !okr || szc != szr || memcmp(wc_buf, wr_buf, (size_t)szc) != 0) {
        say("XCHK FAIL blob load"); ISV("XCHK_DONE\n"); while (1) {}
    }

    /* pse = 0 on both arms: the Physarum router is a global that would let the
     * two models condition each other, and pse = 0 is the configuration the
     * numpy oracle implements (dual_probe.c). */
    sgai_init_ex(&ST_C, wc_buf, SGAI_ENGINE_CPU, &SC_C, 0);
    sgai_init_ex(&ST_R, wr_buf, SGAI_ENGINE_RSP, &SC_R, 0);
    sayf("CPU arm rdy=%d bits=%d L=%d | RSP rdy=%d",
         ST_C.is_loaded, ST_C.w_bits, ST_C.n_layers, ST_R.is_loaded);
    if (!ST_C.is_loaded || !ST_R.is_loaded || !ST_C.kv || !ST_R.kv) {
        say("XCHK FAIL init"); ISV("XCHK_DONE\n"); while (1) {}
    }

    extern uint32_t rsp_mm_calls_rsp, rsp_mm_calls_cpu;
    int all_pass = 1;
    static uint8_t oc[MAXGEN], orr[MAXGEN];
    static char tc[MAXGEN + 1], tr[MAXGEN + 1];

    for (int pi = 0; pi < NPROBES; pi++) {
        const char *p = PROBES[pi].prompt;
        int n = PROBES[pi].ngen;
        uint32_t r0, c0, r1, c1;

        sayf("[%d] \"%s\" x%d tokens", pi, p, n);

        r0 = rsp_mm_calls_rsp; c0 = rsp_mm_calls_cpu;
        uint32_t cp0_c = run_arm(&ST_C, p, n, oc, 1);
        r1 = rsp_mm_calls_rsp; c1 = rsp_mm_calls_cpu;
        uint32_t rsp_in_cpu_arm = r1 - r0; (void)c1; (void)c0;

        r0 = rsp_mm_calls_rsp;
        uint32_t cp0_r = run_arm(&ST_R, p, n, orr, 0);
        r1 = rsp_mm_calls_rsp;
        uint32_t rsp_in_rsp_arm = r1 - r0;

        int first_bad = -1;
        for (int i = 0; i < n; i++) if (oc[i] != orr[i]) { first_bad = i; break; }
        printable(oc, n > 34 ? 34 : n, tc);
        printable(orr, n > 34 ? 34 : n, tr);

        sayf(" CPU: %s", tc);
        sayf(" RSP: %s", tr);
        sayf(" cp0 cpu=%u rsp=%u  x%u.%02u",
             (unsigned)cp0_c, (unsigned)cp0_r,
             (unsigned)(cp0_r ? cp0_c / cp0_r : 0),
             (unsigned)(cp0_r ? (uint64_t)cp0_c * 100 / cp0_r % 100 : 0));
        sayf(" rsp calls: cpu-arm %u  rsp-arm %u",
             (unsigned)rsp_in_cpu_arm, (unsigned)rsp_in_rsp_arm);
        if (first_bad < 0 && rsp_in_cpu_arm == 0 && rsp_in_rsp_arm > 0) {
            sayf(" MATCH %d/%d", n, n);
        } else {
            all_pass = 0;
            if (first_bad >= 0) sayf(" MISMATCH at token %d", first_bad);
            else                say(" ROUTING WRONG (see rsp calls)");
        }

        /* full transcripts to IS-Viewer, untruncated, oracle-comparable */
        { static char full[MAXGEN * 4 + 8]; int m = 0;
          for (int i = 0; i < n; i++) m += sprintf(full + m, "%d ", oc[i]);
          snprintf(pl, sizeof pl, "XCHK[%d] CPU TOKS %s\n", pi, full); ISV(pl);
          m = 0;
          for (int i = 0; i < n; i++) m += sprintf(full + m, "%d ", orr[i]);
          snprintf(pl, sizeof pl, "XCHK[%d] RSP TOKS %s\n", pi, full); ISV(pl); }
    }

    sayf("max |logit gap| = %u e-6 (info)", (unsigned)(g_maxgap * 1000000.0f));
    say(all_pass ? "XCHK PASS - CPU and RSP agree, byte for byte"
                 : "XCHK FAIL");
    ISV("XCHK_DONE\n");
    while (1) { }
}
