#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""gen_cmd_trie.py — emit cmd_trie.h from training/world_defs.py.

GENERATED. Do not hand-edit the header. The trie the ROM decodes with and the
corpus the model is trained on come from ONE file, so a command the world does
not grant is neither taught nor reachable -- the discipline moe_router.h
follows, for the same reason.

Why a mask here is not the cheat we criticised elsewhere: C027 objected to a
lexicon mask for PROSE, because it manufactures coherence the model does not
have. Command SYNTAX is different -- the mask is the parser. A malformed
command, or one naming an item this NPC cannot give, is never emitted rather
than rejected after the fact.
"""
import os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "training"))
import world_defs as W                                   # noqa: E402

def build():
    """Flat trie over command bytes. Node 0 is the root (just after 0x01)."""
    nodes = [{}]            # list of dict: byte -> child index
    accept = [False]
    owner  = [0]            # bitmask of NPCs that may reach this node
    npcs = list(W.NPC_GRANTS)
    for ni, npc in enumerate(npcs):
        bit = 1 << ni
        for verb, args in W.commands_for(npc):
            s = verb + " " + " ".join(args)
            cur = 0
            owner[0] |= bit
            for ch in s.encode():
                if ch not in nodes[cur]:
                    nodes.append({}); accept.append(False); owner.append(0)
                    nodes[cur][ch] = len(nodes) - 1
                cur = nodes[cur][ch]
                owner[cur] |= bit
            accept[cur] = True
    return nodes, accept, owner, npcs

def main():
    nodes, accept, owner, npcs = build()
    edges = []
    starts = []
    for n in nodes:
        starts.append(len(edges))
        for b in sorted(n):
            edges.append((b, n[b]))
    out = ['/* SPDX-License-Identifier: MIT',
           ' * cmd_trie.h — GENERATED by tools/gen_cmd_trie.py from',
           ' * training/world_defs.py. Do not hand-edit.',
           ' *',
           ' * Command grammar, in band with the dialogue:',
           ' *     0x01 verb " " arg [" " arg] 0x02',
           ' * The display band is ASCII 32..126, so both control bytes are',
           ' * invisible to the textbox by construction -- the game routes them',
           ' * to the parser instead, exactly as C028 did for the newline.',
           ' */',
           '#ifndef CMD_TRIE_H', '#define CMD_TRIE_H', '',
           '#include <stdint.h>', '',
           '#define CMD_START 0x01', '#define CMD_END   0x02',
           '#define CMD_NPCS  %d' % len(npcs), '']
    out.append('static const char *const cmd_npc_name[CMD_NPCS] = {')
    out += ['    "%s",' % n for n in npcs]
    out += ['};', '']
    out.append('typedef struct { uint8_t byte; uint16_t child; } CmdEdge;')
    out.append('typedef struct { uint16_t edge0; uint8_t n_edge, accept;')
    out.append('                 uint8_t owner; } CmdNode;   /* owner = NPC bitmask */')
    out.append('')
    out.append('static const CmdEdge cmd_edges[%d] = {' % max(1, len(edges)))
    for b, c in edges:
        ch = chr(b) if 32 <= b < 127 else '?'
        out.append('    { 0x%02x, %4d },   /* %s */' % (b, c, ch))
    if not edges:
        out.append('    { 0, 0 },')
    out += ['};', '']
    out.append('static const CmdNode cmd_nodes[%d] = {' % len(nodes))
    for i, n in enumerate(nodes):
        out.append('    { %4d, %2d, %d, 0x%02x },' %
                   (starts[i], len(n), 1 if accept[i] else 0, owner[i]))
    out += ['};', '',
            '/* Legal next bytes at `node` for `npc`, written into `mask`',
            ' * (256 bytes, 1 = allowed). Returns how many are legal. */',
            'static inline int cmd_legal(int node, int npc, uint8_t *mask)',
            '{',
            '    int n = 0;',
            '    const CmdNode *N = &cmd_nodes[node];',
            '    for (int i = 0; i < N->n_edge; i++) {',
            '        const CmdEdge *e = &cmd_edges[N->edge0 + i];',
            '        if (!(cmd_nodes[e->child].owner & (1u << npc))) continue;',
            '        mask[e->byte] = 1; n++;',
            '    }',
            '    if (N->accept) { mask[CMD_END] = 1; n++; }',
            '    return n;',
            '}', '',
            'static inline int cmd_advance(int node, uint8_t byte)',
            '{',
            '    const CmdNode *N = &cmd_nodes[node];',
            '    for (int i = 0; i < N->n_edge; i++)',
            '        if (cmd_edges[N->edge0 + i].byte == byte)',
            '            return cmd_edges[N->edge0 + i].child;',
            '    return -1;',
            '}', '',
            '#endif /* CMD_TRIE_H */', '']
    path = os.path.join(HERE, "..", "cmd_trie.h")
    open(path, "w").write("\n".join(out))
    print("wrote %s: %d nodes, %d edges, %d NPCs"
          % (os.path.normpath(path), len(nodes), len(edges), len(npcs)))

if __name__ == "__main__":
    main()
