#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""gen_moe_router.py — emit moe_router.h from training/moe_shards.py.

The ROM router and the training labels must perform the IDENTICAL match. If
they drift, a prompt trains into one expert and routes to another at runtime,
and nothing crashes -- the model just answers out of the wrong expert. Deriving
the header from the trainer's own table is what makes that drift impossible.

Usage: python3 tools/gen_moe_router.py [-o moe_router.h]
"""
import argparse, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "training"))
import moe_shards as M                                    # noqa: E402

HEAD = '''/* SPDX-License-Identifier: MIT
 * moe_router.h — GENERATED by tools/gen_moe_router.py from
 * training/moe_shards.py.
 *
 * The ROM router must perform the SAME match the training labels used, or a
 * prompt trains into one expert and routes to another at runtime. Generating
 * this table from the trainer's own list is what makes that impossible; do not
 * hand-edit. Plain lowercase substring, first shard whose keyword hits wins,
 * order matters (specific topics precede general ones).
 */
#ifndef MOE_ROUTER_H
#define MOE_ROUTER_H

#include <string.h>
#include <stdint.h>

'''

TAIL = '''
/* Lowercase a prompt into a bounded scratch buffer, then substring-match. */
static inline uint16_t moe_route(const char *prompt)
{
    char low[96];
    int n = 0;
    for (; prompt[n] && n < (int)sizeof(low) - 1; n++) {
        char c = prompt[n];
        low[n] = (c >= 'A' && c <= 'Z') ? (char)(c - 'A' + 'a') : c;
    }
    low[n] = 0;

    static const char *const *const tabs[] = {
%(TABS)s    };
    for (uint16_t e = 0; e < MOE_N_EXPERTS; e++) {
        const char *const *k = tabs[e];
        if (!k) return e;                 /* the catch-all shard */
        for (; *k; k++) if (strstr(low, *k)) return e;
    }
    return MOE_N_EXPERTS - 1;
}

#endif /* MOE_ROUTER_H */
'''

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("-o", "--out", default=os.path.join(HERE, "..", "moe_router.h"))
    a = ap.parse_args()
    names = [n for n, _ in M.SHARDS]
    o = [HEAD, "#define MOE_N_EXPERTS %d\n" % len(names)]
    for i, n in enumerate(names):
        o.append("#define MOE_E_%s %d\n" % (n.upper(), i))
    o.append("\nstatic const char *const moe_expert_name[MOE_N_EXPERTS] = {\n")
    o += ['    "%s",\n' % n for n in names]
    o.append("};\n\n")
    for n, keys in M.SHARDS:
        if not keys:
            continue
        o.append("static const char *const moe_k_%s[] = {\n" % n)
        o += ['    "%s",\n' % k for k in keys]
        o.append("    0\n};\n")
    tabs = "".join("        %s,\n" % (("moe_k_%s" % n) if keys else "0")
                   for n, keys in M.SHARDS)
    o.append(TAIL % {"TABS": tabs})
    out = os.path.normpath(a.out)
    open(out, "w").write("".join(o))
    print("wrote %s (%d experts: %s)" % (out, len(names), ", ".join(names)))

if __name__ == "__main__":
    main()
